#!/usr/bin/env python
# coding:utf8
import os,time,socket,sys
try:
    import simplejson as json
except:
    import json

status_code = {
    '00' : 'ERROR_STATUS',
    '01' : 'TCP_ESTABLISHED',
    '02' : 'TCP_SYN_SENT',
    '03' : 'TCP_SYN_RECV',
    '04' : 'TCP_FIN_WAIT1',
    '05' : 'TCP_FIN_WAIT2',
    '06' : 'TCP_TIME_WAIT',
    '07' : 'TCP_CLOSE',
    '08' : 'TCP_CLOSE_WAIT',
    '09' : 'TCP_LAST_ACK',
    '0A' : 'TCP_LISTEN',
    '0B' : 'TCP_CLOSING'
}

tcp = "/proc/net/tcp"
con_list = []
tcp_count = {}

#now_time=int(time.time())

for code in status_code.values():
   tcp_count[code] = 0

if os.path.exists(tcp):
    with open(tcp, 'rb') as f:
        lines = f.readlines()
        for line in lines:
            st = line.split()[3]
            for code in status_code.keys():
                if st == code:
                    tcp_count[status_code[code]] += 1

for code in status_code.keys():
    data = {}
    metric = "ss.%s" % status_code[code].lower()
    #data["tags"] = "{}"
    data["metric"] = metric
    data["value"] = tcp_count[status_code[code]]
    data["data_type"] = "gauge"

    con_list.append(data)

#print con_list
print json.dumps(con_list,indent=4)
